version: "3"
services:
  postgres:
    container_name: postgresData
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dataStorageProject
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    container_name: pgadminData
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: