version: "3"
services:
  postgres:
    container_name: postgresData
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dataStorageProject
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres
  pgadmin:
    container_name: pgadminData
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    networks:
      - postgres
    volumes:
      - .backup/:/var/lib/pgadmin/storage/email_gmail.com
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:


#version: "3"
#services:
#  postgres:
#    container_name: postgresContainer
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: testDB
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#    networks:
#      - postgres
#  pgadmin:
#    container_name: pgadminContainer
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: test@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - '5050:80'
#    networks:
#      - postgres
#    volumes:
#      - .backup/:/var/lib/pgadmin/storage/test_gmail.com
#networks:
#  postgres:
#    driver: bridge
#volumes:
#  postgres:
#  pgadmin:
